//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMW.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
            this.AspNetUsers11 = new HashSet<AspNetUser>();
            this.AspNetUsers12 = new HashSet<AspNetUser>();
            this.Comments = new HashSet<Comment>();
            this.Comments1 = new HashSet<Comment>();
            this.Comments2 = new HashSet<Comment>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.Services = new HashSet<Service>();
            this.Services1 = new HashSet<Service>();
            this.Services2 = new HashSet<Service>();
            this.Facilities = new HashSet<Facility>();
            this.Facilities1 = new HashSet<Facility>();
            this.Facilities2 = new HashSet<Facility>();
            this.Properties = new HashSet<Property>();
            this.Properties1 = new HashSet<Property>();
            this.Properties2 = new HashSet<Property>();
            this.Properties3 = new HashSet<Property>();
            this.Properties4 = new HashSet<Property>();
            this.Videos = new HashSet<Video>();
            this.Videos1 = new HashSet<Video>();
            this.Videos2 = new HashSet<Video>();
            this.Videos3 = new HashSet<Video>();
            this.Videos4 = new HashSet<Video>();
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.Projects2 = new HashSet<Project>();
        }
    
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers11 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers12 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Comment> Comments1 { get; set; }
        public virtual ICollection<Comment> Comments2 { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<Service> Services1 { get; set; }
        public virtual ICollection<Service> Services2 { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
        public virtual ICollection<Facility> Facilities1 { get; set; }
        public virtual ICollection<Facility> Facilities2 { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<Property> Properties1 { get; set; }
        public virtual ICollection<Property> Properties2 { get; set; }
        public virtual ICollection<Property> Properties3 { get; set; }
        public virtual ICollection<Property> Properties4 { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
        public virtual ICollection<Video> Videos1 { get; set; }
        public virtual ICollection<Video> Videos2 { get; set; }
        public virtual ICollection<Video> Videos3 { get; set; }
        public virtual ICollection<Video> Videos4 { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual ICollection<Project> Projects2 { get; set; }
    }
}
