//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMW.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public Media()
        {
            this.Comment = new HashSet<Comment>();
            this.Services = new HashSet<Service>();
            this.Facilities = new HashSet<Facility>();
            this.Properties = new HashSet<Property>();
            this.Projects = new HashSet<Project>();
        }
    
        public long MediaId { get; set; }
        public System.Guid MediaGuid { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Path { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> Filesize { get; set; }
        public Nullable<long> MediaTypeId { get; set; }
        public Nullable<long> ExtensionTypeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ExtensionType ExtensionType { get; set; }
        public virtual MediaType MediaType { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
